/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Channels: () => import('#controllers/channels_controller'),
  Communities: () => import('#controllers/communities_controller'),
  Messages: () => import('#controllers/messages_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Oauth: () => import('#controllers/oauth_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Resources: () => import('#controllers/resources_controller'),
  Uploads: () => import('#controllers/uploads_controller'),
}
