/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ChannelSchema extends BaseModel {
  static $columns = ['communityId', 'createdAt', 'id', 'name', 'position', 'topic', 'type', 'updatedAt'] as const
  $columns = ChannelSchema.$columns
  @column()
  declare communityId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare position: number | null
  @column()
  declare topic: string | null
  @column()
  declare type: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CommunitySchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'domainTag', 'iconUrl', 'id', 'isPrivate', 'name', 'ownerId', 'slug', 'updatedAt'] as const
  $columns = CommunitySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare domainTag: string
  @column()
  declare iconUrl: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isPrivate: boolean
  @column()
  declare name: string
  @column()
  declare ownerId: number | null
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CommunityJoinRequestSchema extends BaseModel {
  static $columns = ['communityId', 'createdAt', 'id', 'status', 'updatedAt', 'userId'] as const
  $columns = CommunityJoinRequestSchema.$columns
  @column()
  declare communityId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class CommunityMemberSchema extends BaseModel {
  static $columns = ['communityId', 'createdAt', 'id', 'role', 'updatedAt', 'userId'] as const
  $columns = CommunityMemberSchema.$columns
  @column()
  declare communityId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare role: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class MessageSchema extends BaseModel {
  static $columns = ['channelId', 'content', 'createdAt', 'id', 'parentId', 'reactions', 'updatedAt', 'userId'] as const
  $columns = MessageSchema.$columns
  @column()
  declare channelId: number | null
  @column()
  declare content: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare parentId: number | null
  @column()
  declare reactions: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class ResourceSchema extends BaseModel {
  static $columns = ['communityId', 'createdAt', 'description', 'domainTag', 'id', 'title', 'updatedAt', 'upvotes', 'url', 'userId'] as const
  $columns = ResourceSchema.$columns
  @column()
  declare communityId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare domainTag: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare upvotes: number | null
  @column()
  declare url: string
  @column()
  declare userId: number | null
}

export class UserSchema extends BaseModel {
  static $columns = ['avatarUrl', 'bio', 'createdAt', 'domainInterests', 'email', 'fullName', 'id', 'password', 'status', 'updatedAt', 'username'] as const
  $columns = UserSchema.$columns
  @column()
  declare avatarUrl: string | null
  @column()
  declare bio: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare domainInterests: string | null
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare status: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare username: string | null
}
